/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import example.di.main.GreetingMain;

public class App {
    public static void main(String[] args) {
        GreetingMain.runGreeting();
        GreetingMain.runGreetingByS2Container();
    }
}
